os: Visual Studio 2015

platform: x64

install:
  - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64'
  - choco install strawberryperl
  - SET PATH=C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%
  - git clone https://github.com/tadzik/rakudobrew %USERPROFILE%\rakudobrew
  - SET PATH=%USERPROFILE%\rakudobrew\bin;%PATH%
  # Install rakudostar for faster CI builds. No windows user will actually use
  # rakudobrew
  - choco install rakudostar
  # Refresh environment variables so zef works
  - refreshenv
  # And let us start testing...
  - cd %APPVEYOR_BUILD_FOLDER%

build: off

test_script:
  # Test for fun :)
  - zef install . --verbose

shallow_clone: true
