os: Visual Studio 2015

platform: x64

install:
  # Install rakudostar for faster CI builds. No windows user will actually use
  # rakudobrew
  - choco install rakudostar
  # Refresh environment variables so zef works
  - refreshenv
  # And let us start testing...
  - cd %APPVEYOR_BUILD_FOLDER%

build: off

test_script:
  # Test for fun :)
  - zef install . --verbose

shallow_clone: true
